name: PHP CodeSniffer

on: [push]

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Composer install
        uses: php-actions/composer@v6

      - name: Run PHP CodeSniffer
        uses: php-actions/phpcs@v1
        with:
          php_version: 8.2
          path: /
          standard: phpcs.xml