name: Tests

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5433:5432

    env:
      DB_CONNECTION: pgsql
      DB_HOST: 127.0.0.1
      DB_PORT: 5433
      DB_DATABASE: test
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: xdebug

      - name: Create .env file
        run: |
          echo APP_ENV=testing >> .env
          echo APP_KEY= >> .env

      - name: Install Dependencies
        run: composer install

      - name: Generate app key
        run: php artisan key:generate

      - name: Make migrations
        run: php artisan migrate

      - name: Seed the database with roles and permissions
        run: php artisan db:seed --class=RolesAndPermissionsSeeder

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21

      - name: Install Node.js Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Tests
        run: php artisan test